version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_DB},test
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data
      - ./pg-init-script:/docker-entrypoint-initdb.d

  pgadmin:
    depends_on:
      - postgres
    restart: always
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"

  backend:
    build:
      context: ./
    depends_on:
      - postgres
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - jwtSecret=${jwtSecret}
      - jwtResetSecret=${jwtResetSecret}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - CLIENT_ADDRESS=${CLIENT_ADDRESS}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - 7000:7000
