@host =http://localhost:7000

GET {{host}}

### Get Api
GET {{host}}/api/v1

### Get Users
GET {{host}}/api/v1/users

### Get Products
GET {{host}}/api/v1/products

### Get Products
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "oe@onlineydt.com",
    "password": "010203asd"
}