@host =http://localhost:7000

GET {{host}}

### Get Api
GET {{host}}/api/v1

### Get Users
GET {{host}}/api/v1/users

### Get Exams
GET {{host}}/api/v1/exams

### Login sa
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "oe@onlineydt.com",
    "password": "010203asd"
}

### Register
POST {{host}}/api/v1/auth/register
Content-Type: application/json

{
    "email": "oguzerol1@test.com",
    "password": "010203asd",
    "username": "oguztest1"
}