@host =http://localhost:7000


GET {{host}}

### Get Api
GET {{host}}/api/v1

### Get Users
GET {{host}}/api/v1/users

### Get Exams
GET {{host}}/api/v1/exams

### enroll Exams
POST {{host}}/api/v1/exams/1/enroll
Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6Im9ndXplcm9sIiwiZW1haWwiOiJvZUBvbmxpbmV5ZHQuY29tIiwiaXNfYWRtaW4iOmZhbHNlLCJpc19zdXBlcnVzZXIiOnRydWV9LCJpYXQiOjE2MTI1NjE1NDYsImV4cCI6MTYxMjU4MzE0Nn0.6PNxHDB-tIhTyCFOQsIZOKP5UjrMIreBbgoh4EJrmaM

### Get User Exams
GET {{host}}/api/v1/user/exams
Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6Im9ndXplcm9sIiwiZW1haWwiOiJvZUBvbmxpbmV5ZHQuY29tIiwiaXNfYWRtaW4iOmZhbHNlLCJpc19zdXBlcnVzZXIiOnRydWV9LCJpYXQiOjE2MTQ1NDcwMDAsImV4cCI6MTYxNDU2ODYwMH0.DIAZwHD1L2iwmQZss5e59jiS89Ur-YfpTul-wkHyxrc


### Get User Specific Exams
GET {{host}}/api/v1/user/exams/1
Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6Im9ndXplcm9sIiwiZW1haWwiOiJvZUBvbmxpbmV5ZHQuY29tIiwiaXNfYWRtaW4iOmZhbHNlLCJpc19zdXBlcnVzZXIiOnRydWV9LCJpYXQiOjE2MTUwMjE3MzIsImV4cCI6MTYxNTA0MzMzMn0.u5XWwD-__Bd8xZweiow4ToJD57ZFCC-sBSzs6OVdnd8

### START User Specific Exams
PUT {{host}}/api/v1/user/exams/1/start
Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6Im9ndXplcm9sIiwiZW1haWwiOiJvZUBvbmxpbmV5ZHQuY29tIiwiaXNfYWRtaW4iOmZhbHNlLCJpc19zdXBlcnVzZXIiOnRydWV9LCJpYXQiOjE2MTUxOTkwNzUsImV4cCI6MTYxNTIyMDY3NX0.Jo2OIYIJQM9fMry7LyyYofs471Q5507vstMiGZdVCCE

### END User Specific Exams
PUT {{host}}/api/v1/user/exams/1/end
Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6Im9ndXplcm9sIiwiZW1haWwiOiJvZUBvbmxpbmV5ZHQuY29tIiwiaXNfYWRtaW4iOmZhbHNlLCJpc19zdXBlcnVzZXIiOnRydWV9LCJpYXQiOjE2MTQ2ODU1NzgsImV4cCI6MTYxNDcwNzE3OH0.ewE7vAVJ1_hrffyznH0wr1Kh5X39CBV1Fj1t5VOl7eeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6Im9ndXplcm9sIiwiZW1haWwiOiJvZUBvbmxpbmV5ZHQuY29tIiwiaXNfYWRtaW4iOmZhbHNlLCJpc19zdXBlcnVzZXIiOnRydWV9LCJpYXQiOjE2MTUwMjM0MzQsImV4cCI6MTYxNTA0NTAzNH0.sV-vjY33p6lk4cdoAV6eeKPXwJF9-S-72zwSoNWKNgsY





### Login sa
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "oe@onlineydt.com",
    "password": "010203asd"
}

### Register

POST {{host}}/api/v1/auth/register
Content-Type: application/json

{
    "email": "oguzerol1@test.com",
    "password": "010203asd",
    "username": "oguztest1"
}

### Auth Me
GET {{host}}/api/v1/auth/me
Token:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6Im9ndXplcm9sIiwiZW1haWwiOiJvZUBvbmxpbmV5ZHQuY29tIiwiaXNfYWRtaW4iOmZhbHNlLCJpc19zdXBlcnVzZXIiOnRydWV9LCJpYXQiOjE2MTIzODQ2NzksImV4cCI6MTYxMjQwNjI3OX0.fy81LjNckN-9M0znLtJAHz5AqHTSaJcBSLMUBzNVTMs

### Auth Me
GET {{host}}/api/v1/user/account/me
Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6Im9ndXplcm9sIiwiZW1haWwiOiJvZUBvbmxpbmV5ZHQuY29tIiwiaXNfYWRtaW4iOmZhbHNlLCJpc19zdXBlcnVzZXIiOnRydWV9LCJpYXQiOjE2MTIzMDE5MTUsImV4cCI6MTYxMjMyMzUxNX0.YvNlS9AfFNvHGRF1wYy_I3x8WHetl8mknoUjT8kOubU
